### ISSUE TITLE
Removing a listener can break `trigger`

### ISSUE THREAD

**Issue by rjungemann** [samvv/racket-rx#1]
If you are calling `trigger` quickly and removing listeners frequently, you can run into exceptions like below, because the listener can sometimes not exist in the mutable set as it is looping:

```
hash-iterate-next: no element at index
  index: 5
  context...:
   /Users/admin/Desktop/cacophony/clock.rkt:48:2: for-loop
```

Here's a fix I'm using in my code, although there may be a better way:

```racket
(define (trigger evt . args)
  (define l (set->list (event-emitter-listeners evt)))
  (for ([callback l])
    (apply callback args)))
```
